owncloud:
  image: schoeffm/rpi-nextcloud:9.0.53
  ports:
    - "80:80"
    - "443:443"
  links:
    - db:mysql
  volumes_from:
    - data 
  environment:
    OWNCLOUD_SERVERNAME: dockerpi
db:
  image: schoeffm/rpi-nextcloud-mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: stefan
    OWNCLOUD_DB_USER: golem
    OWNCLOUD_DB_PASSWORD: golem
data:
  image: schoeffm/rpi-nextcloud-data
  environment:
    OWNCLOUD_DB_USER: golem
    OWNCLOUD_DB_PASSWORD: golem